language: node_js
node_js:
  - "0.12"
notifications:
  webhooks:
    secure: "OISQeyASHba0D27zEnCZ/u/h/VYZoWlWYilLpdWNulfezKKZb52roZ/gNt+Rrnl5caIZsWwIImWdI1ySizlWsFpkDm/dm+kCvXytynYvf0Z5VdVot+cQJQWbjl619DLKJHYAWsVXJjtYTZ2pVTBNOy3ctCgGordOUwir5h2Y5+E="

